### ISSUE TITLE
Duplicate helper functions: __vue_normalize__ & __vue_create_injector__

### ISSUE THREAD

**Issue by fjc0k** [vuejs/rollup-plugin-vue#210]
use rollup-plugin-vue to transform `app.vue`:
```
<script>
import App2 from './app2.vue'
export default {
  render(h) {
    return h(App2)
  }
}
</script>
```

### Expected behavior
```js
function __vue_normalize__() {}
function __vue_create_injector__() {}
```
### Actual behavior
```js
function __vue_normalize__() {}
function __vue_create_injector__() {}
function __vue_normalize__$1() {}
function __vue_create_injector__$1() {}
```
### Steps to reproduce the behavior
If a Vue component library has a large number of components, rollup is not that much cheaper than webpack.

**Comment by YunSun-CN** [comment]
@znck Please note that if option `css: false` was specified, dead code `__vue_create_injector__` and `__vue_create_injector_ssr__` were also generated. And please do not add arguments to function `__vue_normalize__` if not needed, since optimization tools like `uglify-es` cannot remove dead code entirely.

**Comment by znck** [comment]
Version 4.4.0-alpha.0 is published with external assemble helpers. 

Could you please try that? Waiting on feedback if this approach is helpful.

**Comment by egoist** [comment]
using latest version `4.3.2` with `css: false`, and there're still unnecessary helpers like `__vue_create_injector__`
