### ISSUE TITLE
Document cssModules in gh-pages/configuration

### ISSUE THREAD

**Issue by macu** [vuejs/rollup-plugin-vue#66]
Please add documentation for the 'cssModules' configuration option. Also update master/test/test.js which uses 'modules'. You should also demo this in your example build. `generateScopedName: '[name]__[hash:base64:5]'` :+1:

**Comment by znck** [comment]
Docs for 2.3 are not ready yet. Working on it.

**Comment by tomsarduy** [comment]
**Great to see a project like this**, exactly something I was looking for this morning, but more info in the `README.md` with more explicit example codes would be great. Some people don't know what's [rollup](rollupjs.org) and what's the difference with webpack for example. Why should we use this instead of tweaking the webpack config to get separated reusable bundles?

**Comment by znck** [comment]
🎉  Docs are updated.

> PRs welcome for adding examples & description about rollup.

-----
Keeping it open until v2.3 is released.
